#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="infra/docker-compose.single-host.yaml"
PROJECT_NAME="quant-hft-single-host"
ENV_FILE="infra/env/prodlike.env"
TIMESCALE_SERVICE="timescale-primary"
TIMESCALE_DB="quant_hft"
TIMESCALE_USER="quant_hft"
FROM_DATE_UTC="$(date -u +%Y-%m-%d)"
DAYS_BACKFILL=1
DAYS_AHEAD=7
DOCKER_BIN="docker"
READY_TIMEOUT_SEC=120
READY_POLL_INTERVAL_SEC=2
OUTPUT_FILE="docs/results/ensure_trading_partitions_result.env"
DRY_RUN=1

usage() {
  cat <<USAGE
Usage: $0 [options]

Options:
  --compose-file <path>           Docker compose file path
  --project-name <name>           Compose project name
  --env-file <path>               Optional env file passed to compose
  --timescale-service <name>      Timescale service name (default: timescale-primary)
  --timescale-db <name>           Timescale database name (default: quant_hft)
  --timescale-user <name>         Timescale database user (default: quant_hft)
  --from-date-utc <YYYY-MM-DD>    Partition anchor date in UTC (default: today UTC)
  --days-backfill <n>             Create partitions for N days before anchor (default: 1)
  --days-ahead <n>                Create partitions for N days after anchor (default: 7)
  --ready-timeout-sec <sec>       Wait timeout for pg_isready (default: 120)
  --ready-poll-interval-sec <sec> Poll interval for pg_isready (default: 2)
  --output-file <path>            Evidence env output path
  --docker-bin <path>             Docker binary (default: docker)
  --dry-run                       Print commands and write simulated evidence (default)
  --execute                       Execute commands
  -h, --help                      Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --compose-file)
      COMPOSE_FILE="${2:-}"
      shift 2
      ;;
    --project-name)
      PROJECT_NAME="${2:-}"
      shift 2
      ;;
    --env-file)
      ENV_FILE="${2:-}"
      shift 2
      ;;
    --timescale-service)
      TIMESCALE_SERVICE="${2:-}"
      shift 2
      ;;
    --timescale-db)
      TIMESCALE_DB="${2:-}"
      shift 2
      ;;
    --timescale-user)
      TIMESCALE_USER="${2:-}"
      shift 2
      ;;
    --from-date-utc)
      FROM_DATE_UTC="${2:-}"
      shift 2
      ;;
    --days-backfill)
      DAYS_BACKFILL="${2:-}"
      shift 2
      ;;
    --days-ahead)
      DAYS_AHEAD="${2:-}"
      shift 2
      ;;
    --ready-timeout-sec)
      READY_TIMEOUT_SEC="${2:-}"
      shift 2
      ;;
    --ready-poll-interval-sec)
      READY_POLL_INTERVAL_SEC="${2:-}"
      shift 2
      ;;
    --output-file)
      OUTPUT_FILE="${2:-}"
      shift 2
      ;;
    --docker-bin)
      DOCKER_BIN="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --execute)
      DRY_RUN=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "$COMPOSE_FILE" ]]; then
  echo "error: compose file not found: $COMPOSE_FILE" >&2
  exit 2
fi
if ! [[ "$DAYS_BACKFILL" =~ ^[0-9]+$ ]]; then
  echo "error: --days-backfill must be a non-negative integer" >&2
  exit 2
fi
if ! [[ "$DAYS_AHEAD" =~ ^[0-9]+$ ]]; then
  echo "error: --days-ahead must be a non-negative integer" >&2
  exit 2
fi

# Validate date input.
if ! date -u -d "$FROM_DATE_UTC" +%Y-%m-%d >/dev/null 2>&1; then
  echo "error: --from-date-utc must be a valid date, got: $FROM_DATE_UTC" >&2
  exit 2
fi
FROM_DATE_UTC="$(date -u -d "$FROM_DATE_UTC" +%Y-%m-%d)"

compose_base=("$DOCKER_BIN" "compose" "-f" "$COMPOSE_FILE" "--project-name" "$PROJECT_NAME")
if [[ -n "$ENV_FILE" && -f "$ENV_FILE" ]]; then
  compose_base+=("--env-file" "$ENV_FILE")
fi

tmp_sql="$(mktemp)"
cleanup() {
  rm -f "$tmp_sql"
}
trap cleanup EXIT

expected_days=$((DAYS_BACKFILL + DAYS_AHEAD + 1))
expected_partitions=$((expected_days * 2))

{
  echo "-- Generated by ensure_trading_partitions.sh"
  echo "BEGIN;"
  for ((offset=-DAYS_BACKFILL; offset<=DAYS_AHEAD; ++offset)); do
    day="$(date -u -d "$FROM_DATE_UTC $offset day" +%Y-%m-%d)"
    next_day="$(date -u -d "$day +1 day" +%Y-%m-%d)"
    suffix="$(date -u -d "$day" +%Y%m%d)"
    cat <<SQL
CREATE TABLE IF NOT EXISTS trading_core.order_events_p${suffix}
    PARTITION OF trading_core.order_events
    FOR VALUES FROM ('${day}') TO ('${next_day}');
CREATE TABLE IF NOT EXISTS trading_core.trade_events_p${suffix}
    PARTITION OF trading_core.trade_events
    FOR VALUES FROM ('${day}') TO ('${next_day}');
SQL
  done
  echo "COMMIT;"
} > "$tmp_sql"

wait_ready_command="${compose_base[*]} exec -T $TIMESCALE_SERVICE pg_isready -U $TIMESCALE_USER -d $TIMESCALE_DB (timeout=${READY_TIMEOUT_SEC}s interval=${READY_POLL_INTERVAL_SEC}s)"
apply_command="${compose_base[*]} exec -T $TIMESCALE_SERVICE psql -v ON_ERROR_STOP=1 -U $TIMESCALE_USER -d $TIMESCALE_DB < $tmp_sql"
verify_sql="SELECT COUNT(*) FROM pg_class child JOIN pg_namespace child_ns ON child.relnamespace = child_ns.oid JOIN pg_inherits inh ON inh.inhrelid = child.oid JOIN pg_class parent ON parent.oid = inh.inhparent JOIN pg_namespace parent_ns ON parent.relnamespace = parent_ns.oid WHERE parent_ns.nspname='trading_core' AND parent.relname IN ('order_events','trade_events') AND child.relname ~ '_p[0-9]{8}$';"
verify_command="${compose_base[*]} exec -T $TIMESCALE_SERVICE psql -t -A -U $TIMESCALE_USER -d $TIMESCALE_DB -c \"$verify_sql\" (expect >= ${expected_partitions})"

steps_name=("wait_ready" "apply_partitions" "verify_partitions")
steps_cmd=("$wait_ready_command" "$apply_command" "$verify_command")
steps_status=()
steps_duration_ms=()
failed_step=""

run_step_wait_ready() {
  local elapsed=0
  while (( elapsed <= READY_TIMEOUT_SEC )); do
    if "${compose_base[@]}" exec -T "$TIMESCALE_SERVICE" \
      pg_isready -U "$TIMESCALE_USER" -d "$TIMESCALE_DB" >/dev/null 2>&1; then
      return 0
    fi
    sleep "$READY_POLL_INTERVAL_SEC"
    elapsed=$((elapsed + READY_POLL_INTERVAL_SEC))
  done
  return 1
}

run_step_apply() {
  "${compose_base[@]}" exec -T "$TIMESCALE_SERVICE" \
    psql -v ON_ERROR_STOP=1 -U "$TIMESCALE_USER" -d "$TIMESCALE_DB" < "$tmp_sql"
}

run_step_verify() {
  local count
  count=$("${compose_base[@]}" exec -T "$TIMESCALE_SERVICE" \
    psql -t -A -U "$TIMESCALE_USER" -d "$TIMESCALE_DB" -c "$verify_sql")
  count="$(echo "$count" | tr -d '[:space:]')"
  if [[ -z "$count" ]]; then
    return 1
  fi
  if (( count < expected_partitions )); then
    return 1
  fi
  return 0
}

for idx in "${!steps_name[@]}"; do
  name="${steps_name[$idx]}"
  command_text="${steps_cmd[$idx]}"
  started_ns=$(date +%s%N)

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] $command_text"
    status="simulated_ok"
  else
    set +e
    if [[ "$name" == "wait_ready" ]]; then
      run_step_wait_ready
    elif [[ "$name" == "apply_partitions" ]]; then
      run_step_apply
    else
      run_step_verify
    fi
    rc=$?
    set -e
    if [[ $rc -eq 0 ]]; then
      status="ok"
    else
      status="failed"
      if [[ -z "$failed_step" ]]; then
        failed_step="$name"
      fi
    fi
  fi

  finished_ns=$(date +%s%N)
  elapsed_ms=$(( (finished_ns - started_ns) / 1000000 ))
  if [[ $elapsed_ms -lt 0 ]]; then
    elapsed_ms=0
  fi

  steps_status+=("$status")
  steps_duration_ms+=("$elapsed_ms")

  if [[ "$status" == "failed" ]]; then
    break
  fi
done

success="true"
if [[ -n "$failed_step" ]]; then
  success="false"
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"
{
  echo "ENSURE_TRADING_PARTITIONS_DRY_RUN=$([[ "$DRY_RUN" -eq 1 ]] && echo 1 || echo 0)"
  echo "ENSURE_TRADING_PARTITIONS_SUCCESS=$success"
  echo "ENSURE_TRADING_PARTITIONS_FAILED_STEP=$failed_step"
  echo "ENSURE_TRADING_PARTITIONS_COMPOSE_FILE=$COMPOSE_FILE"
  echo "ENSURE_TRADING_PARTITIONS_PROJECT_NAME=$PROJECT_NAME"
  echo "ENSURE_TRADING_PARTITIONS_ENV_FILE=$ENV_FILE"
  echo "ENSURE_TRADING_PARTITIONS_SERVICE=$TIMESCALE_SERVICE"
  echo "ENSURE_TRADING_PARTITIONS_DB=$TIMESCALE_DB"
  echo "ENSURE_TRADING_PARTITIONS_USER=$TIMESCALE_USER"
  echo "ENSURE_TRADING_PARTITIONS_FROM_DATE_UTC=$FROM_DATE_UTC"
  echo "ENSURE_TRADING_PARTITIONS_DAYS_BACKFILL=$DAYS_BACKFILL"
  echo "ENSURE_TRADING_PARTITIONS_DAYS_AHEAD=$DAYS_AHEAD"
  echo "ENSURE_TRADING_PARTITIONS_EXPECTED_PARTITIONS=$expected_partitions"
  echo "ENSURE_TRADING_PARTITIONS_TOTAL_STEPS=${#steps_status[@]}"
  for idx in "${!steps_status[@]}"; do
    n=$((idx + 1))
    echo "STEP_${n}_NAME=${steps_name[$idx]}"
    echo "STEP_${n}_STATUS=${steps_status[$idx]}"
    echo "STEP_${n}_DURATION_MS=${steps_duration_ms[$idx]}"
    echo "STEP_${n}_COMMAND=${steps_cmd[$idx]}"
  done
} > "$OUTPUT_FILE"

echo "$OUTPUT_FILE"
if [[ "$success" == "true" ]]; then
  exit 0
fi
exit 2
