if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/backtest_data_feed_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/backtest_data_feed_test[1]_tests.cmake")
else()
  add_test(backtest_data_feed_test_NOT_BUILT backtest_data_feed_test_NOT_BUILT)
endif()
