# CMake generated Testfile for 
# Source directory: /home/kevin0923/workspace/quant_platform_HF
# Build directory: /home/kevin0923/workspace/quant_platform_HF/build-pybind
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/query_scheduler_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_config_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_config_loader_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_gateway_adapter_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_trader_adapter_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_md_adapter_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/wal_replay_loader_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/redis_realtime_store_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/timescale_event_store_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/redis_realtime_store_client_adapter_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/timescale_event_store_client_adapter_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/storage_client_pool_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/timescale_buffered_event_store_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/storage_client_factory_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/tcp_redis_hash_client_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/strategy_intent_inbox_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/libpq_timescale_sql_client_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/trading_ledger_store_client_adapter_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/trading_domain_store_client_adapter_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/object_pool_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/event_object_pool_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/market_bus_producer_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/event_dispatcher_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/flow_controller_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/circuit_breaker_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/fixed_decimal_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/basic_risk_engine_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/risk_policy_engine_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/in_memory_portfolio_ledger_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_position_ledger_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_account_ledger_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/self_trade_risk_engine_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/risk_rule_executor_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/rate_limiter_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/risk_manager_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/bar_aggregator_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/order_state_machine_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/execution_planner_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/execution_router_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/execution_engine_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/order_manager_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/position_manager_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/settlement_query_client_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/settlement_price_provider_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/daily_settlement_service_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/rule_market_state_engine_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/metric_registry_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/parquet_data_feed_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/backtest_data_feed_test[1]_include.cmake")
include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/live_data_feed_test[1]_include.cmake")
subdirs("_deps/googletest-build")
