if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_config_loader_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_config_loader_test[1]_tests.cmake")
else()
  add_test(ctp_config_loader_test_NOT_BUILT ctp_config_loader_test_NOT_BUILT)
endif()
