if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_account_ledger_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/ctp_account_ledger_test[1]_tests.cmake")
else()
  add_test(ctp_account_ledger_test_NOT_BUILT ctp_account_ledger_test_NOT_BUILT)
endif()
