if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/execution_planner_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/execution_planner_test[1]_tests.cmake")
else()
  add_test(execution_planner_test_NOT_BUILT execution_planner_test_NOT_BUILT)
endif()
