if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/flow_controller_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/flow_controller_test[1]_tests.cmake")
else()
  add_test(flow_controller_test_NOT_BUILT flow_controller_test_NOT_BUILT)
endif()
