if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/in_memory_portfolio_ledger_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/in_memory_portfolio_ledger_test[1]_tests.cmake")
else()
  add_test(in_memory_portfolio_ledger_test_NOT_BUILT in_memory_portfolio_ledger_test_NOT_BUILT)
endif()
