if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/libpq_timescale_sql_client_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/libpq_timescale_sql_client_test[1]_tests.cmake")
else()
  add_test(libpq_timescale_sql_client_test_NOT_BUILT libpq_timescale_sql_client_test_NOT_BUILT)
endif()
