if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/live_data_feed_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/live_data_feed_test[1]_tests.cmake")
else()
  add_test(live_data_feed_test_NOT_BUILT live_data_feed_test_NOT_BUILT)
endif()
