if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/metric_registry_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/metric_registry_test[1]_tests.cmake")
else()
  add_test(metric_registry_test_NOT_BUILT metric_registry_test_NOT_BUILT)
endif()
