if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/parquet_data_feed_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/parquet_data_feed_test[1]_tests.cmake")
else()
  add_test(parquet_data_feed_test_NOT_BUILT parquet_data_feed_test_NOT_BUILT)
endif()
