if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/position_manager_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/position_manager_test[1]_tests.cmake")
else()
  add_test(position_manager_test_NOT_BUILT position_manager_test_NOT_BUILT)
endif()
