if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/query_scheduler_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/query_scheduler_test[1]_tests.cmake")
else()
  add_test(query_scheduler_test_NOT_BUILT query_scheduler_test_NOT_BUILT)
endif()
