if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/rate_limiter_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/rate_limiter_test[1]_tests.cmake")
else()
  add_test(rate_limiter_test_NOT_BUILT rate_limiter_test_NOT_BUILT)
endif()
