if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/rule_market_state_engine_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/rule_market_state_engine_test[1]_tests.cmake")
else()
  add_test(rule_market_state_engine_test_NOT_BUILT rule_market_state_engine_test_NOT_BUILT)
endif()
