if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/self_trade_risk_engine_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/self_trade_risk_engine_test[1]_tests.cmake")
else()
  add_test(self_trade_risk_engine_test_NOT_BUILT self_trade_risk_engine_test_NOT_BUILT)
endif()
