if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/settlement_price_provider_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/settlement_price_provider_test[1]_tests.cmake")
else()
  add_test(settlement_price_provider_test_NOT_BUILT settlement_price_provider_test_NOT_BUILT)
endif()
