if(EXISTS "/home/kevin0923/workspace/quant_platform_HF/build-pybind/settlement_query_client_test[1]_tests.cmake")
  include("/home/kevin0923/workspace/quant_platform_HF/build-pybind/settlement_query_client_test[1]_tests.cmake")
else()
  add_test(settlement_query_client_test_NOT_BUILT settlement_query_client_test_NOT_BUILT)
endif()
