# Both consumers build from installed, immutable dependencies only.
set(_lock_file "${CMAKE_CURRENT_LIST_DIR}/../dependencies.lock.json")
if(NOT EXISTS "${_lock_file}")
    message(FATAL_ERROR "Missing dependencies.lock.json")
endif()
file(READ "${_lock_file}" _lock)
string(JSON _expected_version GET "${_lock}" version)
if(NOT "${QuantStrategies_VERSION}" STREQUAL "${_expected_version}")
    message(FATAL_ERROR "QuantStrategies version differs from dependency lock")
endif()
string(JSON _expected_hash GET "${_lock}" manifest_sha256)
set(_manifest_path "${QuantStrategies_DATA_DIR}/manifest.json")
file(SHA256 "${_manifest_path}" _actual_hash)
if(NOT "${_expected_hash}" STREQUAL "${_actual_hash}")
    message(FATAL_ERROR "QuantStrategies manifest checksum differs from dependency lock")
endif()
get_filename_component(_installed_root "${QuantStrategies_DIR}/../../.." REALPATH)
file(READ "${_manifest_path}" _manifest)
string(JSON _file_count LENGTH "${_manifest}" files)
math(EXPR _last "${_file_count} - 1")
foreach(_index RANGE 0 ${_last})
    string(JSON _relative MEMBER "${_manifest}" files ${_index})
    if(IS_ABSOLUTE "${_relative}" OR _relative MATCHES "(^|/)\\.\\.(/|$)")
        message(FATAL_ERROR "Unsafe path in package manifest")
    endif()
    string(JSON _expected GET "${_manifest}" files "${_relative}")
    file(SHA256 "${_installed_root}/${_relative}" _actual)
    if(NOT "${_expected}" STREQUAL "${_actual}")
        message(FATAL_ERROR "Installed dependency modified: ${_relative}")
    endif()
endforeach()
set(QUANT_STRATEGIES_MANIFEST_SHA256 "${_actual_hash}")
